config/routes.rb
Arthmitee::Application.routes.draw do

  root 'static_pages#home'

  get '/services', to: "static_pages#services"
  get '/clients', to: "static_pages#clients"
  get '/contact', to: "static_pages#contact"
  get '/team', to: "static_pages#team"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home
	end

	def services
	end
	
	def about_us
	end

	def clients
	end

	def team
	end

	def contact
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.haml
/ === Footer ===
.footer{id:'footer'}
  .container
    .row
      .col-md-4.md-margin-bottom-40
        / About
        .headline
          %h2 About
        %p.margin-bottom-25.md-margin-bottom-40 
          Foodninja is the platform for all awesome foodies to share their knowledge about foods
      / /col-md-4
      .col-md-4.md-margin-bottom-40
      
      / /col-md-4
      .col-md-4
        / Monthly Newsletter
        .headline
          %h2 Contact Us
        %address.md-margin-bottom-40
          25, Lorem Lis Street, Orange
          %br/
          California, US
          %br/
          Phone: 800 123 3456
          %br/
          Fax: 800 123 3456
          %br/
          Email:
          %a{href: "mailto:info@anybiz.com"} info@anybiz.com
      / /col-md-4
    / /row
  / /container
/ /footer
/ === End Footer ===
/ === Copyright ===
.copyright
  .container
    .row
      .col-md-6
        %p.copyright-space
          2013 © Edunable. ALL Rights Reserved.
          %a{href: "#"} Privacy Policy
          |
          %a{href: "#"} Terms of Service
      .col-md-6
        %a{href: "index.html"}
          %img#logo-footer.pull-right{alt: "", src: "assets/img/logo2-default.png"}/
    / /row
  / /container
/ /copyright
/ === End Copyright ===
/ JS Global Compulsory

app/views/layouts/_header.html.haml
/ /top
/ === End Top ===
/ === Header ===
.header
  .navbar.navbar-default{role: "navigation"}
    .container
      / Brand and toggle get grouped for better mobile display
      .navbar-header
        %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", type: "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{href: root_path}
          =image_tag('logo1-default.png')
      / Collect the nav links, forms, and other content for toggling
      .collapse.navbar-collapse.navbar-responsive-collapse
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            %a.dropdown-toggle{"data-close-others" => "false", "data-delay" => "0", "data-hover" => "dropdown",  href: root_path}
              Home
          %li
            =link_to "Services offered", services_path, class: 'dropdown-toggle', "data-close-others" => "false", "data-delay" => "0", "data-hover" => "dropdown"
          %li
            =link_to "Clients", clients_path
          %li
            =link_to "Our Team", team_path  
          %li
            =link_to "Contact Us", contact_path
          %li
            -# if user_signed_in?
              =#link_to 'Sign out', destroy_user_session_path, method: :delete
            -#else
              =#link_to('Login', new_user_session_path)

          %li.dropdown
            -# %a.dropdown-toggle{"data-close-others" => "false", "data-delay" => "0", "data-hover" => "dropdown", href: opportunities_path}
            -# Opportunities
          
          %li.dropdown
            -#if user_signed_in?
              -#%a.dropdown-toggle{"data-close-others" => "false", "data-delay" => "0", "data-hover" => "dropdown", href: edit_user_path(current_user.id)}
                -#Profile
            -#else
              -#%a.dropdown-toggle{"data-close-others" => "false", "data-delay" => "0", "data-hover" => "dropdown", href: new_user_registration_path}
                -#Register
  
          / /input-group
      / /navbar-collapse
/ /header

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Arthmitee</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<%= yield %>
	<%= render 'layouts/footer' %>
</body>
</html>

app/views/static_pages/about_us.html.haml
/ === Content Part ===
.container
  .margin-bottom-50
    %img.img-responsive{alt: "", src: "assets/img/sliders/revolution/bg8.jpg"}/
  .tag-box.tag-box-v2
    %h2 About Our Company
    %p Et harum quidem rerum facilis est et expedita distinctio lorem ipsum dolor sit amet consectetur adipiscing elit. Ut non libero consectetur adipiscing elit magna. Sed et quam lacus. Fusce condimentum eleifend enim a feugiat. Pellentesque viverra vehicula sem ut volutpat.
  .margin-bottom-20.clearfix
  .row
    / Accordion
    .col-md-7.md-margin-bottom-40
      #accordion-1.panel-group.acc-v1
        .panel.panel-default
          .panel-heading
            %h4.panel-title
              %a.accordion-toggle{"data-parent" => "#accordion-1", "data-toggle" => "collapse", href: "#collapse-One"}
                Collapsible Group Item #1
          #collapse-One.panel-collapse.collapse.in
            .panel-body
              .row
                .col-md-4
                  %img.img-responsive{alt: "", src: "assets/img/new/img5.jpg"}/
                .col-md-8
                  Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et.
        .panel.panel-default
          .panel-heading
            %h4.panel-title
              %a.accordion-toggle{"data-parent" => "#accordion-1", "data-toggle" => "collapse", href: "#collapse-Two"}
                Collapsible Group Item #2
          #collapse-Two.panel-collapse.collapse
            .panel-body
              .row
                .col-md-8
                  %p Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.
                  %ul.list-unstyled
                    %li
                      %i.icon-ok.color-green
                      Donec id elit non mi porta gravida at eget metus..
                    %li
                      %i.icon-ok.color-green
                      Fusce dapibus, tellus ac cursus comodo egetine..
                    %li
                      %i.icon-ok.color-green
                      Food truck quinoa nesciunt laborum eiusmod runch..
                .col-md-4
                  %img.img-responsive{alt: "", src: "assets/img/main/6.jpg"}/
        .panel.panel-default
          .panel-heading
            %h4.panel-title
              %a.accordion-toggle{"data-parent" => "#accordion-1", "data-toggle" => "collapse", href: "#collapse-Three"}
                Collapsible Group Item #3
          #collapse-Three.panel-collapse.collapse
            .panel-body
              Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Food truck quinoa nesciunt laborum eiusmodolf moon tempor, sunt aliqua put a bird. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
    / End Accordion
    / Testimonials
    .col-md-5
      #testimonials-1.carousel.slide.testimonials.testimonials-v1
        .carousel-inner
          .item.active
            %p Crasjusto ducimus qui cupiditate non provident, similique sunt in culpaid est anditiis praesentium praesentium blanditiis praesentium non provident, similique sunt in culpaid est anditiis praesentium praesentium..
            .testimonial-info
              %img{alt: "", src: "assets/img/testimonials/img1.jpg"}/
              %span.testimonial-author
                Jeremy Asigner
                %em Web Developer, Unify Theme.
          .item
            %p Crasjusto ducimus qui cupiditate non provident, similique sunt in culpaid est anditiis praesentium praesentium blanditiis praesentium non provident, similique sunt in culpaid est anditiis praesentium praesentium..
            .testimonial-info
              %img{alt: "", src: "assets/img/testimonials/user.jpg"}/
              %span.testimonial-author
                User
                %em Java Developer, Htmlstream
          .item
            %p Crasjusto ducimus qui cupiditate non provident, similique sunt in culpaid est anditiis praesentium praesentium blanditiis praesentium non provident, similique sunt in culpaid est anditiis praesentium praesentium..
            .testimonial-info
              %img{alt: "", src: "assets/img/testimonials/img2.jpg"}/
              %span.testimonial-author
                Kate Davenport
                %em Web Designer, Google Inc.
        .carousel-arrow
          %a.left.carousel-control{"data-slide" => "prev", href: "#testimonials-1"}
            %i.icon-angle-left
          %a.right.carousel-control{"data-slide" => "next", href: "#testimonials-1"}
            %i.icon-angle-right
    / End Testimonials
  .margin-bottom-50
  / Our Team
  .headline
    %h2 Meet Our Team
  .row.team
    .col-sm-3
      .thumbnail-style
        %img.img-responsive{alt: "", src: "assets/img/team/1.jpg"}/
        %h3
          %a Jack Bour
          %small Chief Executive Officer
        %p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, justo sit amet risus etiam porta sem...
        %ul.list-unstyled.list-inline.team-socail
          %li
            %a{href: "#"}
              %i.icon-facebook
          %li
            %a{href: "#"}
              %i.icon-twitter
          %li
            %a{href: "#"}
              %i.icon-google-plus
    .col-sm-3
      .thumbnail-style
        %img.img-responsive{alt: "", src: "assets/img/team/3.jpg"}/
        %h3
          %a Kate Metus
          %small Project Manager
        %p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, justo sit amet risus etiam porta sem...
        %ul.list-unstyled.list-inline.team-socail
          %li
            %a{href: "#"}
              %i.icon-facebook
          %li
            %a{href: "#"}
              %i.icon-twitter
          %li
            %a{href: "#"}
              %i.icon-google-plus
    .col-sm-3
      .thumbnail-style
        %img.img-responsive{alt: "", src: "assets/img/team/2.jpg"}/
        %h3
          %a Porta Gravida
          %small VP of Operations
        %p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, justo sit amet risus etiam porta sem...
        %ul.list-unstyled.list-inline.team-socail
          %li
            %a{href: "#"}
              %i.icon-facebook
          %li
            %a{href: "#"}
              %i.icon-twitter
          %li
            %a{href: "#"}
              %i.icon-google-plus
    .col-sm-3
      .thumbnail-style
        %img.img-responsive{alt: "", src: "assets/img/team/4.jpg"}/
        %h3
          %a Donec Elit
          %small Director, R & D Talent
        %p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, justo sit amet risus etiam porta sem...
        %ul.list-unstyled.list-inline.team-socail
          %li
            %a{href: "#"}
              %i.icon-facebook
          %li
            %a{href: "#"}
              %i.icon-twitter
          %li
            %a{href: "#"}
              %i.icon-google-plus
  / /team
  / End Our Team
  / Our Clients
  #clients-flexslider.flexslider.home.clients
    .headline
      %h2 Our Clients
    %ul.slides
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/hp_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/hp.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/igneus_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/igneus.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/vadafone_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/vadafone.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/walmart_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/walmart.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/shell_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/shell.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/natural_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/natural.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/aztec_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/aztec.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/gamescast_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/gamescast.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/cisco_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/cisco.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/everyday_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/everyday.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/cocacola_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/cocacola.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/spinworkx_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/spinworkx.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/shell_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/shell.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/natural_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/natural.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/gamescast_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/gamescast.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/everyday_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/everyday.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/spinworkx_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/spinworkx.png"}/
  / /flexslider
  / End Our Clients
/ /container
/ === End Content Part ===

app/views/static_pages/clients.html.haml
/ === Content Part ===
.container
  .row
    .col-md-9
      .headline
        %h2 Our Clinets
      .clients-page.margin-bottom-20
        %a.img-hover{href: "#"}
          %img{alt: "", src: "assets/img/clients/cisco_grey.png"}/
          %img.img-colorful{alt: "", src: "assets/img/clients/cisco.png"}/
        %p
          At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est etenim a feugiat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut non libero magna. Sed et quam lacus. Fusce condimentum eleifend enim a feugiat. Pellentesque viverra vehicula sem ut volutpat. Integer sed arcu.
          %a.linked.color-green{href: "#"} htttp://www.example.com
      .clients-page.margin-bottom-20
        %a.img-hover{href: "#"}
          %img{alt: "", src: "assets/img/clients/cocacola_grey.png"}/
          %img.img-colorful{alt: "", src: "assets/img/clients/cocacola.png"}/
        %p
          At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est etenim a feugiat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut non libero magna. Sed et quam lacus. Fusce condimentum eleifend enim a feugiat. Pellentesque viverra vehicula sem ut volutpat. Integer sed arcu.
          %a.linked.color-green{href: "#"} http://www.example.com
      .clients-page.margin-bottom-20
        %a.img-hover{href: "#"}
          %img{alt: "", src: "assets/img/clients/hp_grey.png"}/
          %img.img-colorful{alt: "", src: "assets/img/clients/hp.png"}/
        %p
          At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est etenim a feugiat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut non libero magna. Sed et quam lacus. Fusce condimentum eleifend enim a feugiat. Pellentesque viverra vehicula sem ut volutpat. Integer sed arcu.
          %a.linked.color-green{href: "#"} http://www.example.com
      .clients-page.margin-bottom-20
        %a.img-hover{href: "#"}
          %img{alt: "", src: "assets/img/clients/shell_grey.png"}/
          %img.img-colorful{alt: "", src: "assets/img/clients/shell.png"}/
        %p
          At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est etenim a feugiat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut non libero magna. Sed et quam lacus. Fusce condimentum eleifend enim a feugiat. Pellentesque viverra vehicula sem ut volutpat. Integer sed arcu.
          %a.linked.color-green{href: "#"} http://www.example.com
      .clients-page.margin-bottom-20
        %a.img-hover{href: "#"}
          %img{alt: "", src: "assets/img/clients/vadafone_grey.png"}/
          %img.img-colorful{alt: "", src: "assets/img/clients/vadafone.png"}/
        %p
          At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est etenim a feugiat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut non libero magna. Sed et quam lacus. Fusce condimentum eleifend enim a feugiat. Pellentesque viverra vehicula sem ut volutpat. Integer sed arcu.
          %a.linked.color-green{href: "#"} http://www.example.com
    / /col-md-9
    .col-md-3
      / Our Services
      .who.margin-bottom-30
        .headline
          %h2 Our Services
        %p At vero eos et accusamus et iusto odio dign issimos ducimus qui blanditiis iusto.
        %ul.list-unstyled
          %li
            %a{href: "#"}
              %i.icon-desktop>
              Vivamus imperdiet condimentum
          %li
            %a{href: "#"}
              %i.icon-bullhorn>
              Anim pariatur cliche squid
          %li
            %a{href: "#"}
              %i.icon-globe>
              Eget placerat felis consectetur
          %li
            %a{href: "#"}
              %i.icon-group>
              Condimentum diam eget placerat
      / About Us
      .headline
        %h2 About Us
      %p.margin-bottom-30
        At vero eos et acc usamus et iusto odio dign issimos ducimus atque corrupti quos dolores etrerum facilis est etenim a feugiat cupiditate non quos.
        %a.read-more{href: "#"} Read more
      / Contact Us
      .who.margin-bottom-30
        .headline
          %h2 Contact Us
        %p Vero facilis est etenim a feugiat cupiditate non quos etrerum facilis.
        %ul.list-unstyled
          %li
            %a{href: "#"}
              %i.icon-home>
              5B amus ED554, New York, US
          %li
            %a{href: "#"}
              %i.icon-envelope-alt>
              infp@example.com
          %li
            %a{href: "#"}
              %i.icon-phone-sign>
              1(222) 5x86 x97x
          %li
            %a{href: "#"}
              %i.icon-globe>
              http://www.example.com
    / /col-md-3
  / /row
/ /container
/ === End Content Part ===

app/views/static_pages/contact.html.haml
/ === Content Part ===
.container
  .row.margin-bottom-30
    .col-md-9.mb-margin-bottom-30
      / Google Map
      #map.map.map-box.map-box-space.margin-bottom-40
      / -/map
      / End Google Map
      %p At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas feugiat. Et harum quidem rerum facilis est et expedita distinctio lorem ipsum dolor sit amet, consectetur adipiscing elit landitiis.
      %br/
      %form
        %label Name
        .row.margin-bottom-20
          .col-md-7.col-md-offset-0
            %input.form-control{type: "text"}/
        %label
          Email
          %span.color-red *
        .row.margin-bottom-20
          .col-md-7.col-md-offset-0
            %input.form-control{type: "text"}/
        %label Message
        .row.margin-bottom-20
          .col-md-11.col-md-offset-0
            %textarea.form-control{rows: "8"}
        %p
          %button.btn-u{type: "submit"} Send Message
    / /col-md-9
    .col-md-3
      / Contacts
      .headline
        %h2 Contacts
      %ul.list-unstyled.who.margin-bottom-30
        %li
          %a{href: "#"}
            %i.icon-home>
            5B Streat, City 50987 New Town US
        %li
          %a{href: "#"}
            %i.icon-envelope-alt>
            info@example.com
        %li
          %a{href: "#"}
            %i.icon-phone-sign>
            1(222) 5x86 x97x
        %li
          %a{href: "#"}
            %i.icon-globe>
            http://www.example.com
      / Business Hours
      .headline
        %h2 Business Hours
      %ul.list-unstyled.margin-bottom-30
        %li
          %strong Monday-Friday:
          10am to 8pm
        %li
          %strong Saturday:
          11am to 3pm
        %li
          %strong Sunday:
          Closed
      / Why we are?
      .headline
        %h2 Why we are?
      %p At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum.
      %ul.list-unstyled
        %li
          %i.icon-ok.color-green
          Odio dignissimos ducimus
        %li
          %i.icon-ok.color-green
          Blanditiis praesentium volup
        %li
          %i.icon-ok.color-green
          Eos et accusamus
    / /col-md-3
  / /row
  / Our Clients
  #clients-flexslider.flexslider.home.clients
    .headline
      %h2 Our Clients
    %ul.slides
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/hp_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/hp.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/igneus_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/igneus.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/vadafone_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/vadafone.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/walmart_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/walmart.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/shell_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/shell.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/natural_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/natural.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/aztec_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/aztec.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/gamescast_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/gamescast.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/cisco_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/cisco.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/everyday_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/everyday.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/cocacola_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/cocacola.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/spinworkx_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/spinworkx.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/shell_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/shell.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/natural_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/natural.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/gamescast_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/gamescast.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/everyday_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/everyday.png"}/
      %li
        %a{href: "#"}
          %img{alt: "", src: "assets/img/clients/spinworkx_grey.png"}/
          %img.color-img{alt: "", src: "assets/img/clients/spinworkx.png"}/
  / /flexslider
  / End Our Clients
/ /container
/ === End Content Part ===